refresh_rate = "30 seconds"

[appenders.file]
kind = "rolling_file"  #console file rolling_file
path = "log/stellar.log"

[appenders.file.encoder]
kind = "pattern"
pattern = "[{l}] {d(%Y-%m-%d %H:%M:%S)} {M} {L} - {m} {n}"

[appenders.file.policy]
kind = "compound"   #

[appenders.file.policy.trigger]
kind = "size"
limit = "100mb"  #kb mb gb

[appenders.file.policy.roller]
kind = "fixed_window"  #delete  fixed_window
pattern = "log/stellar-{}.log"
base = 0
count = 100

[root]
level = "info"
appenders = ["file"]  #file stdout
