refresh_rate = "30 seconds"

[appenders.file]
kind = "file"
path = "log/stellar.log"

[appenders.file.encoder]
kind = "pattern"
pattern = "{l} {d(%Y-%m-%d %H:%M:%S)} {M} {L} - {m} {n}"

[root]
level = "info"
appenders = ["file"]
