[package]
name = "siege"
version = "0.1.0"
authors = ["yk2011 <yike19911102@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.111"
serde_qs = "0.6.0"
serde_derive = "1.0.111"